[package]
name = "shiguredo_avm"
version = "2026.0.0"
edition = "2024"
rust-version = "1.88"
description = "Rust bindings for AVM (Alliance for Video Media) codec library"
readme = "README.md"
homepage = "https://github.com/shiguredo/avm-rs"
repository = "https://github.com/shiguredo/avm-rs"
license = "Apache-2.0"
build = "build.rs"
include = ["/LICENSE", "/README.md", "/build.rs", "/src/**/*"]

# 以降は外部ライブラリビルド用のメタデータ
# (この内容は build.rs の中からのみ参照される)
[package.metadata.external-dependencies]
avm = { url = "https://github.com/AOMediaCodec/avm.git", version = "v1.0.0" }

[[example]]
name = "encoder"
path = "examples/encoder.rs"

[[example]]
name = "decoder"
path = "examples/decoder.rs"

[dependencies]

[build-dependencies]
bindgen = "0.72"
shiguredo_cmake = "4.3"
shiguredo_toml = "2026.2"

[features]
source-build = []
